FROM node:16-alpine
RUN mkdir -p /home/node/app
#WORKDIR /home/node/app 
WORKDIR '/app'
#COPY --chown=node:node ./package.json ./
COPY package.json .
RUN npm install
COPY . .
#COPY --chown=node:node ./ ./


CMD ["npm", "run", "start"]
